#!/bin/bash
RED='\033[0;31m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
WHITE='\033[1;37m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
LCYAN='\033[1;36m'
NC='\033[0m' # No Color
BOLD=$(tput bold)
NORM=$(tput sgr0)

echo -e "${GREEN}${BOLD}---Fullup--- Update Script by William Houser${NC}${NORM}" &&
sleep 2s &&
echo -e "${YELLOW}${BOLD}Updating Package Archives${NC}${NORM}" &&
sudo apt update &&
echo -e "${YELLOW}${BOLD}Performing Full System Upgrade${NC}${NORM}" &&
sudo apt full-upgrade -y &&
echo -e "${YELLOW}${BOLD}Performing Autoremove${NC}${NORM}" &&
sudo apt autoremove -y &&
echo -e "${RED}${BOLD}System Update Complete!!${NC}${NORM}"
end 0
